# DEPLOY
server.port=${PORT:8080}

# SECURITY
server.error.include-stacktrace=never
logging.level.org.springframework.security=INFO

# DB
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate

# REDIS
spring.data.redis.url=${REDIS_URL}